### PR TITLE
Pass extra link arguments to all linked targets

### PR DESCRIPTION
**Pull request by nshp**
Still missing the build.rs keywords to choose more specifically which targets link args should be applied to, but the main PR mentions we can do that later.

Need anything else?

### CODE REVIEW

**Comment by nshp** [comment]
@reitermarkus -- ping?

Rebased onto upstream master again to fix the merge conflict. I can just move this to an upstream PR if you're no longer focused on it.

**Comment by reitermarkus** [comment]
Thanks for the ping, I didn't get a notification about this because apparently forks aren't watched automatically. I'll rebase my branch.

**Comment by reitermarkus** [comment]
Thanks, @nshp! I cherry-picked this in https://github.com/reitermarkus/cargo/commit/3a603e773dfc42b3b0005bad4eb1336ddefd06fd.

**Comment by nshp** [comment]
@reitermarkus Looks like the documentation patch was lost to the git-merge ether somehow:
```
diff --git a/src/doc/src/reference/unstable.md b/src/doc/src/reference/unstable.md
index 4fdaca896..1710779bd 100644
--- a/src/doc/src/reference/unstable.md
+++ b/src/doc/src/reference/unstable.md
@@ -29,7 +29,8 @@ in build scripts:
 * [`cargo:rustc-link-arg-bins=FLAG`](#rustc-link-arg-bins) — Passes custom
   flags to a linker for bin crates.
 * [`cargo:rustc-link-arg=FLAG`](#rustc-link-arg) — Passes custom
-  flags to a linker for all supported crates.
+  flags to a linker for `cdylib` crates, `bin` crates, examples binaries,
+  benchmarks, and tests.

 <a id="rustc-link-arg-bins"></a>
 #### `cargo:rustc-link-arg-bins=FLAG`
```

Feel free to just commit that yourself if you think it's valuable.

**Pull request closed without merging**
